[package]
name = "iron"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "1"
regex = "*"
regex-macro = "0.1.1"
serde = { version = "1", features = ["derive"] }
llvm-sys = "120.0.0"